spring:
  application:
    name: API-SERVICE
  main:
    banner_mode: 'off'
    allow-bean-definition-overriding: true
  cloud:
    config:
      discovery:
        service-id: API-SERVICE

server:
  port: 8087


keycloak:
  #auth-server-url: http://localhost:8180/auth
  auth-server-url: http://cef07.hitss.com.br/auth
  credentials:
    secret: '123456'
  public-client: false
  realm: api-gateway
  resource: service-user
  ssl-required: none
  securityConstraints:
    - authRoles:
        - user
        - master
      securityCollections:
        - name: user-roles
          patterns:
            - /secure/user
    - authRoles:
        - master
      securityCollections:
        - name: master-roles
          patterns:
            - /secure/master
logging:
  level.org.keycloak: DEBUG
  level.org.apache.catalina.authenticator: DEBUG
  level.de.ctrlaltdel: DEBUG

eureka:
  client:
    serviceUrl:
      #defaultZone: ${EUREKA_URI:http://34.95.224.180:8761/eureka}
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  ribbon:
    eureka:
      enabled: true
    http:
      client:
        enabled: true